/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:228803:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:228803:

public void button1_click1(GButton source, GEvent event) { //_CODE_:playButton:689059:
  println("playButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:playButton:689059:

public void button2_click1(GButton source, GEvent event) { //_CODE_:playButton:403109:
  println("playButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:playButton:403109:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  imgButton1 = new GImageButton(this, 11, -3, 472, 321, new String[] { "", "", "" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  playButton = new GButton(this, 149, 148, 207, 34);
  playButton.setText("Play");
  playButton.setTextBold();
  playButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  playButton.addEventHandler(this, "button1_click1");
  playButton = new GButton(this, 148, 204, 207, 34);
  playButton.setText("Exit");
  playButton.setTextBold();
  playButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  playButton.addEventHandler(this, "button2_click1");
  sketchPad1 = new GSketchPad(this, 167, 50, 173, 81);
}

// Variable declarations 
// autogenerated do not edit
GImageButton imgButton1; 
GButton playButton; 

GSketchPad sketchPad1; 